import Head from "next/head";
import styles from "../styles/Home.module.css";
import React from "react";
import Data from "../data/list.json";
import Card from "../pages/components/List";
import Image from "next/image";
import profilePic from "../public/pp.png";
import { motion } from "framer-motion";

/**
 * @return {JSX.Element}
 */
export default function Home() {
  // console.log(Data.Data);
  // const { ref, inView } = useInView({
  //   threshold: 0.2
  // });
  // const animation = useAnimation();
  // useEffect(() => {
  //   if (inView) {
  //     animation.start({
  //       x: 0,
  //       transition: {
  //         type: "spring",
  //         duration: 2.5,
  //       },
  //     });
  //   }else{
  //     animation.start({
  //       x: "-400px",
  //     });

  //   }
  // });
  const spring = {
    type: "spring",
    duration: 2,
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title> as
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.snapping + " " + styles.code}>
        <div className={styles.children}>
          <div>
            <div className="relative z-10 overflow-hidden p-2 ">
              <div className={styles.fadeinname + " text-center text-7xl"}>
                Aqsyal Raihan Jamil
              </div>
            </div>
            <div className="relative z-10  overflow-hidden">
              <div className={styles.fadein + " text-center text-3xl mt-12"}>
                Fresh Graduate Web Developer
              </div>
            </div>
          </div>
        </div>
        <div className={"!w-3/4 " + styles.children + "  box-border mx-auto"}>
          <div className="mx-auto w-2/3 max-w-xl relative z-10">
            <motion.div
              initial={{ x: "-400px" }}
              whileInView={{ x: 0 }}
              transition={spring}
              className="mx-auto w-full max-w-xl relative -z-10"
            >
              <h1
                className={
                  "absolute text-9xl pointer-events-none -top-20 text-opacity-60 -left-16 max-w-md text-gray-300 -z-10 font-black " +
                  styles.monts
                }
              >
                ABOUT ME
              </h1>
            </motion.div>
            <p className="text-xl">
              Hello, i&apos;m Aqsyal Raihan Jamil. Former vocational highschool
              student. My interest with web development started there, and has
              become my lifelong joy. In this website, you&apos;ll discover my
              journey through some project / achievement / challenge that
              i&apos;ve been done or still developing.
              {/* Lorem Ipsum is simply dummy text of the printing and typesetting
              industry. Lorem Ipsum has been the industry&apos;s standard dummy
              text ever since the 1500s, when an unknown printer took a galley
              of type and scrambled it to make a type specimen book. It has
              survived not only five centuries, but also the leap into
              electronic typesetting, remaining essentially unchanged. */}
            </p>
          </div>
          <div className="max-w-md w-1/4 mx-auto">
            <Image src={profilePic} alt="Profile" placeholder="blur" />
          </div>
        </div>
        {Data.Data.map((data: any, key: number) => (
          <Card key={key} data={data} />
        ))}
      </div>
    </div>
  );
}
